#!/usr/bin/env node
// deploy.js — CDK deploy + admin console build + S3 upload + CloudFront invalidation.
// Usage: node deploy.js  OR  npm run deploy

const fs   = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const configPath = path.join(__dirname, 'deploy.config.yaml');
if (!fs.existsSync(configPath)) {
  console.error('\nError: deploy.config.yaml not found.');
  console.error('Copy deploy.config.example.yaml to deploy.config.yaml and fill in your values.\n');
  process.exit(1);
}

const run = (cmd, opts = {}) => execSync(cmd, { stdio: 'inherit', ...opts });

// ── 1. CDK deploy ────────────────────────────────────────────────────────────

const cdkBin = process.platform === 'win32'
  ? path.join(__dirname, 'node_modules', '.bin', 'cdk.cmd')
  : path.join(__dirname, 'node_modules', '.bin', 'cdk');

run(`"${cdkBin}" deploy MsightCloudStack --require-approval never`);

// ── 2. Read CloudFormation outputs ───────────────────────────────────────────

console.log('\n── Reading CloudFormation outputs…');

const describeRaw = execSync(
  'aws cloudformation describe-stacks --stack-name MsightCloudStack --query "Stacks[0].Outputs"',
  { encoding: 'utf8' }
);
const outputs = JSON.parse(describeRaw);
const out = {};
for (const { OutputKey, OutputValue } of outputs) out[OutputKey] = OutputValue;

const region             = process.env.AWS_DEFAULT_REGION || process.env.AWS_REGION || 'us-east-2';
const adminApiUrl        = out.AdminApiUrl;
const userPoolId         = out.AdminUserPoolId;
const userPoolClientId   = out.AdminUserPoolClientId;
const bucketName         = out.AdminConsoleBucketName;
const distributionId     = out.AdminConsoleDistributionId;
const consoleUrl         = out.AdminConsoleUrl;

if (!adminApiUrl || !userPoolId || !userPoolClientId || !bucketName || !distributionId) {
  console.error('Missing expected CloudFormation outputs. Check the stack deployed correctly.');
  process.exit(1);
}

// ── 3. Write admin-console/.env ──────────────────────────────────────────────

const consoleDir = path.join(__dirname, 'admin-console');
const envPath    = path.join(consoleDir, '.env');

const envContent = [
  '# Generated by deploy.js on every deploy. Do not edit — your changes will',
  '# be overwritten. Values come from the CloudFormation stack outputs.',
  `VITE_AWS_REGION=${region}`,
  `VITE_USER_POOL_ID=${userPoolId}`,
  `VITE_USER_POOL_CLIENT_ID=${userPoolClientId}`,
  `VITE_ADMIN_API_URL=${adminApiUrl}`,
  '',
].join('\n');

fs.writeFileSync(envPath, envContent, 'utf8');
console.log(`Wrote ${envPath}`);

// ── 4. Build the admin console ───────────────────────────────────────────────

console.log('\n── Building admin console…');
run('npm run build', { cwd: consoleDir });

// ── 5. Sync to S3 ────────────────────────────────────────────────────────────

const distDir = path.join(consoleDir, 'dist', 'spa');

console.log(`\n── Uploading to s3://${bucketName}…`);

// index.html — no-cache so browsers always fetch the latest shell
run(
  `aws s3 cp "${distDir}/index.html" "s3://${bucketName}/index.html" ` +
  `--cache-control "no-cache, no-store, must-revalidate" --content-type "text/html"`
);

// Everything else — assets have content-hashed filenames, safe to cache forever
run(
  `aws s3 sync "${distDir}" "s3://${bucketName}" ` +
  `--exclude "index.html" ` +
  `--cache-control "public, max-age=31536000, immutable" ` +
  `--delete`
);

// ── 6. Invalidate CloudFront ─────────────────────────────────────────────────

console.log(`\n── Invalidating CloudFront distribution ${distributionId}…`);
run(
  `aws cloudfront create-invalidation --distribution-id ${distributionId} --paths "/*"`
);

console.log(`\n✅  Console live at ${consoleUrl}\n`);
