/**
 * Refuses to start rather than falling back to a default.
 *
 * A console pointed at the wrong account is worse than one that will not
 * load: it signs in against a Cognito pool that is not the deployment's, and
 * every page then reports the wrong deployment's state as though it were this
 * one's.
 *
 * The message names the normal fix first. `.env` is generated by `deploy.js`
 * from the stack's CloudFormation outputs, so "missing" almost always means
 * this checkout has never deployed — not that somebody forgot to fill a form
 * in. The message used to name only `.env.example`, which did not exist at
 * the time, sending the reader to look for a file that was never there.
 */
function required(name: string, value: string | undefined): string {
  if (!value) {
    throw new Error(
      `Missing ${name}. Run "npm run deploy" from the repository root — it writes ` +
        'admin-console/.env from the stack outputs. To work on the console against a ' +
        'deployment you are not deploying to, copy admin-console/.env.example to .env ' +
        'and fill it in from the stack outputs instead.'
    );
  }
  return value;
}

export const config = {
  region: required('VITE_AWS_REGION', import.meta.env.VITE_AWS_REGION),
  userPoolId: required('VITE_USER_POOL_ID', import.meta.env.VITE_USER_POOL_ID),
  userPoolClientId: required(
    'VITE_USER_POOL_CLIENT_ID',
    import.meta.env.VITE_USER_POOL_CLIENT_ID
  ),
  adminApiUrl: required('VITE_ADMIN_API_URL', import.meta.env.VITE_ADMIN_API_URL).replace(
    /\/+$/,
    ''
  ),
};
